title: MovingPandas 

description: A Python library for movement data exploration and analysis

theme: minima

minima:
  # generate social links in footer
  social_links:
    twitter: underdarkGIS
    github:  anitagraser
