title: MovingPandas 
author:
  name: Anita Graser
  email: anitagraser@gmx.at

description: A Python libarary for movement data exploration and analysis

theme: minima

minima:
  # generate social links in footer
  social_links:
    twitter: underdarkGIS
    github:  anitagraser
