name: movingpandas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - cython
  - matplotlib
  - seaborn
  - pandas
  - geopandas
  - rasterio
  - hvplot
  - proj
  - cartopy
