name: movingpandas_docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - shapely
  - fiona
  - rtree
  - geopy
  - matplotlib
  - mapclassify
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - ipython
  - pillow
  - mock
  - rasterio
  - geoplot
  - sphinx-gallery
  - jinja2
  - doc2dash

